version: "3.9"

services:
  app:
    build: .
    container_name: npec_app
    restart: always

    ports:
      - "8000:8000"

    environment:
      MONGO_URL: mongodb+srv://<npec>:<xLjaJCTkHjv5R448>@npec.5kslodu.mongodb.net/?appName=NPEC
      DATABASE_NAME: npec
